### ISSUE TITLE
Adding Node.js 4 support

### ISSUE THREAD

**Issue by zkochan** [sholladay/find-down#1]
I'd like to use this package but it has some Node 6 syntax. Node 4 is LTS until April 2018. Any objections to adding Node 4 support to find-down?

**Comment by sholladay** [comment]
No objections. I implemented `async` / `await` in https://github.com/sholladay/find-down/commit/9e20e4245f1db56e6da06376f417cc3c0babbeb6 and then, mistakenly, released it as `0.1.3` when I should have done `0.2.0` (breaking changes < 1.x increment the minor).

The most correct thing to do right now would be to revert that commit, check to make sure `engines` in package.json can be `>=4` rather than `>=6` (it was only that way because I hadn't tested on Node 4), and then publish `0.1.4` with the older syntax. I can consider releasing a `1.0.0` with `async` / `await` at a later time.

**Comment by sholladay** [comment]
@zkochan `0.1.4` has been released with Node 4 support

**Comment by zkochan** [comment]
Thanks, it works now. You might want to bump version to 1.0.0. It seems stable enough.

**Comment by sholladay** [comment]
I would love to, but not going to do that until we have [AVA](https://github.com/avajs/ava) tests. Just haven't gotten around to it yet. If you are sufficiently motivated, a pull request would be greatly appreciated!
